sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t testing_image .

script:
  - docker run testing_image npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-649156420025"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id:
    secure: "$AWS_SECRET_KEY"
